import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react'

export type Language = 'en' | 'sv' | 'es' | 'fr' | 'de' | 'it' | 'ru' | 'zh'

const STORAGE_KEY = 'ecoroute-language'

const supportedLanguages: Language[] = ['en', 'sv', 'es', 'fr', 'de', 'it', 'ru', 'zh']

const languageLabels: Record<Language, string> = {
  en: 'English',
  sv: 'Svenska',
  es: 'Español',
  fr: 'Français',
  de: 'Deutsch',
  it: 'Italiano',
  ru: 'Русский',
  zh: '中文',
}

const englishTranslations = {
  navbarHome: 'Home',
  navbarPlanner: 'Planner',
  navbarAbout: 'About',
  navbarHistory: 'My History',
  navbarMenuOpen: 'Open menu',
  navbarMenuClose: 'Close menu',
  languageSwitch: 'Language',

  authLoading: 'Loading...',
  authLogIn: 'Log In',
  authLogOut: 'Log Out',
  authSignUp: 'Sign Up',

  loginTabLogIn: 'Log In',
  loginTabSignUp: 'Sign Up',
  loginEmail: 'Email',
  loginPassword: 'Password',
  loginEmailPlaceholder: 'you@example.com',
  loginPasswordPlaceholder: '••••••••',
  loginCancel: 'Cancel',
  loginError: 'An error occurred',

  landingBadge: 'Sustainable Travel Planner',
  landingTitleLine1: 'Travel smarter.',
  landingTitleLine2: 'Know your carbon footprint.',
  landingDescription: 'Compare emissions from flights, trains and cars across the world.',
  landingPlanRoute: 'Plan your route →',
  landingHowItWorks: 'How it works',
  landingFeaturesTitle: 'Why EcoRoute?',
  landingSaveJourneysTitle: 'Save your journeys',
  landingSaveJourneysDesc:
    'Create a free account to track your routes, monitor your carbon footprint over time, and revisit past comparisons.',
  landingCreateAccount: 'Create free account',
  landingAlreadyHaveAccount: 'Already have an account? Log in',
  landingBottomTitle: 'Ready to plan a greener journey?',
  landingBottomDesc: 'Start comparing routes and discover how much CO₂ you can save.',
  landingOpenPlanner: 'Open the planner →',
  landingFeatureFlightTitle: 'Flight Emissions',
  landingFeatureFlightDesc:
    'Calculate exact CO₂ output per flight using ICAO-certified methodology, cabin class multipliers, and RFI.',
  landingFeatureAlternativesTitle: 'Greener Alternatives',
  landingFeatureAlternativesDesc:
    'Discover lower-emission train and multi-modal routes across Europe as alternatives to flying.',
  landingFeatureCompareTitle: 'Side-by-Side Compare',
  landingFeatureCompareDesc:
    'See flights and alternatives together — emissions, distance, and eco-impact all at a glance.',
  landingFeatureHistoryTitle: 'Journey History',
  landingFeatureHistoryDesc:
    'Log in to save routes, track your total carbon footprint, and monitor your travel habits over time.',

  aboutBadge: 'About',
  aboutTitle: 'About EcoRoute',
  aboutIntro:
    'EcoRoute is a student project designed to make travel emissions visible and comparable. We believe informed choices drive change — knowing the environmental impact of your journey helps you make decisions aligned with your values.',
  aboutMissionTitle: 'Our mission',
  aboutMission:
    'We are working toward UN Sustainable Development Goal 13 (Climate Action) by providing accessible, accurate emissions data for air and ground travel. Rather than estimate emissions ourselves, we rely on authoritative external data sources so the numbers you see are as reliable as possible.',
  aboutHowItWorksTitle: 'How it works',
  aboutFlightEmissionsTitle: 'Flight emissions — Google Travel Impact Model (TIM)',
  aboutFlightEmissions:
    "All flight CO₂ figures come from Google's Travel Impact Model API. TIM is an open-source model that uses real aircraft types, seat configurations, load factors, and routing data to estimate per-passenger emissions by cabin class. It also reports a contrails impact bucket (Low / Moderate / High) to indicate the non-CO₂ warming contribution of a specific flight.",
  aboutFlightDistanceTitle: 'Flight route distance',
  aboutFlightDistance:
    'is calculated locally using the Haversine formula between airports, with a 95 km detour factor added for real-world routing. This is used for display purposes only — the emissions figure itself comes from TIM.',
  aboutCarDistanceTitle: 'Car route distance',
  aboutCarDistance:
    'is fetched from the OSRM API (Open Source Routing Machine), which returns the actual road distance and driving time between two cities. Emissions are then calculated by applying a factor of 0.21 kg CO₂ per km, based on a typical European passenger car.',
  aboutTrainTitle: 'Train comparison',
  aboutTrain:
    'uses the straight-line distance between cities with an emission factor of 0.041 kg CO₂ per km, reflecting average European rail emissions including the electricity grid mix.',
  aboutCompareTitle: 'Compare your options',
  aboutCompare:
    'EcoRoute lets you compare the emissions of a flight with car and train alternatives side by side. Use the planner to understand the true climate cost of your journey and discover lower-impact ways to travel.',

  accountLoggedOut: 'You must be logged in to view your history.',
  accountLabel: 'Account',
  accountTitle: 'My history',
  accountLoading: 'Loading history…',
  accountNoHistory: 'No history yet.',
  accountNoHistoryHint:
    'Plan a journey on the home page and it will be saved here automatically.',
  accountSavedTrips: '{count} saved trips',
  accountClearAll: 'Clear all',
  accountConfirmClear: 'Are you sure you want to clear all history?',
  accountRemove: 'Remove',

  plannerLabel: 'EcoRoute Planner',
  plannerTitle: 'Flight emissions planner',
  plannerHideMap: 'Hide map',
  plannerShowMap: 'Show map',
  plannerFavorites: 'Favorites',
  plannerLoad: 'Load',
  plannerUseCurrentLocationLoading: 'Getting location...',
  plannerUseCurrentLocation: 'Use Current Location',
  plannerSaveToHistory: 'Save to history',
  plannerSaveAsFavorite: 'Save as favorite',
  plannerGeoUnsupported: 'Geolocation is not supported by this browser.',
  plannerGeoLoading: 'Getting your current location...',
  plannerGeoUsingLocation: 'Using your current location: {city}, {country}',
  plannerGeoDenied: 'Location access denied. Please allow location access to use this feature.',
  plannerGeoUnavailable: 'Location information is unavailable.',
  plannerGeoTimeout: 'Location request timed out.',
  plannerGeoError: 'Unable to get your location.',
  plannerSavedHistory: 'Flight saved to history.',
  plannerSavedFavorite: 'Saved as favorite.',

  cityFrom: 'From',
  cityTo: 'To',
  citySearchPlaceholder: 'Search country, city, or airport code…',
  citySearchAria: '{label} city and country search',
  cityTopResults: 'Showing top 50 results. Narrow your search for more specific choices.',
  cityNoMatches: 'No matching cities found.',

  travelCabinClass: 'Cabin class',
  travelEconomy: 'Economy',
  travelBusiness: 'Business',
  travelFirst: 'First',
  travelNumberOfTravelers: 'Number of travelers',

  emissionsFetching: 'Fetching emissions from TIM API…',
  emissionsEstimateWarning: 'Live data unavailable — showing estimate based on standard emission factors',
  emissionsTitle: 'CO₂ emissions',
  emissionsPerPerson: 'Per person:',
  emissionsFlightDistance: 'flight distance (incl. routing)',
  emissionsDrivingEquivalent: 'by car',
  emissionsTreesNeeded: 'tree{suffix} needed to offset (1 year)',
  emissionsTravelersTotal: 'traveler{suffix} total',

  comparisonTitle: 'Mode comparison',
  comparisonFlight: 'Flight',
  comparisonCar: 'Car',
  comparisonTrain: 'Train',

  legsDirectFlight: 'Direct flight',
  legsFlightRoute: 'Flight route · {count} legs',

  flightHistoryEmptyTitle: 'No flights saved yet',
  flightHistoryEmptyHint: 'Search for a flight to add to your history',
  flightHistoryTitle: 'Your Flight History ({count})',
  flightHistoryClearAll: 'Clear All History',
  flightHistoryDelete: 'Delete',
  mapHideAirports: 'Hide airports',
  mapShowAirports: 'Show airports',
  mapTransferLabel: 'Transfer:',
} as const

export type TranslationKey = keyof typeof englishTranslations

type TranslationParams = Record<string, string | number>

type TranslationMap = Partial<Record<TranslationKey, string>>

const translations: Record<Language, TranslationMap> = {
  en: englishTranslations,
  sv: {
    navbarHome: 'Hem',
    navbarPlanner: 'Planerare',
    navbarAbout: 'Om',
    navbarHistory: 'Min historik',
    navbarMenuOpen: 'Öppna meny',
    navbarMenuClose: 'Stäng meny',
    languageSwitch: 'Språk',
    authLoading: 'Laddar...',
    authLogIn: 'Logga in',
    authLogOut: 'Logga ut',
    authSignUp: 'Registrera dig',
    loginTabLogIn: 'Logga in',
    loginTabSignUp: 'Registrera dig',
    loginEmail: 'E-post',
    loginPassword: 'Lösenord',
    loginEmailPlaceholder: 'du@exempel.se',
    loginPasswordPlaceholder: '••••••••',
    loginCancel: 'Avbryt',
    loginError: 'Ett fel uppstod',
    landingBadge: 'Hållbar reseplanerare',
    landingTitleLine1: 'Res smartare.',
    landingTitleLine2: 'Se ditt koldioxidavtryck.',
    landingDescription: 'Jämför utsläpp från flyg, tåg och bil över hela världen.',
    landingPlanRoute: 'Planera din resa →',
    landingHowItWorks: 'Så fungerar det',
    landingFeaturesTitle: 'Varför EcoRoute?',
    landingSaveJourneysTitle: 'Spara dina resor',
    landingSaveJourneysDesc:
      'Skapa ett gratis konto för att följa dina resor, övervaka ditt koldioxidavtryck över tid och återbesöka tidigare jämförelser.',
    landingCreateAccount: 'Skapa gratis konto',
    landingAlreadyHaveAccount: 'Har du redan ett konto? Logga in',
    landingBottomTitle: 'Redo att planera en grönare resa?',
    landingBottomDesc: 'Börja jämföra rutter och se hur mycket CO₂ du kan spara.',
    landingOpenPlanner: 'Öppna planeraren →',
    landingFeatureFlightTitle: 'Flygutsläpp',
    landingFeatureFlightDesc:
      'Beräkna exakt CO₂-utsläpp per flyg med ICAO-certifierad metodik, kabinklassmultiplikatorer och RFI.',
    landingFeatureAlternativesTitle: 'Grönare alternativ',
    landingFeatureAlternativesDesc:
      'Upptäck tåg- och multimodala rutter med lägre utsläpp över Europa som alternativ till att flyga.',
    landingFeatureCompareTitle: 'Jämför sida vid sida',
    landingFeatureCompareDesc:
      'Se flyg och alternativ tillsammans — utsläpp, avstånd och klimatpåverkan i en överblick.',
    landingFeatureHistoryTitle: 'Reshistorik',
    landingFeatureHistoryDesc:
      'Logga in för att spara rutter, följa ditt totala koldioxidavtryck och se dina resvanor över tid.',
    aboutBadge: 'Om',
    aboutTitle: 'Om EcoRoute',
    aboutIntro:
      'EcoRoute är ett studentprojekt som gör reseutsläpp synliga och jämförbara. Vi tror att välgrundade val driver förändring — att känna till klimatpåverkan från din resa hjälper dig att fatta beslut som stämmer med dina värderingar.',
    aboutMissionTitle: 'Vårt uppdrag',
    aboutMission:
      'Vi arbetar mot FN:s globala mål 13 (Bekämpa klimatförändringarna) genom att tillhandahålla tillgänglig och korrekt utsläppsdata för flyg och markresor. I stället för att uppskatta utsläppen själva lutar vi oss mot auktoritativa externa datakällor så att siffrorna du ser är så tillförlitliga som möjligt.',
    aboutHowItWorksTitle: 'Så fungerar det',
    aboutFlightEmissionsTitle: 'Flygutsläpp — Google Travel Impact Model (TIM)',
    aboutFlightEmissions:
      'Alla flyg-CO₂-värden kommer från Googles Travel Impact Model API. TIM är en open source-modell som använder verkliga flygplanstyper, sittkonfigurationer, beläggningsgrader och ruttdata för att uppskatta utsläpp per passagerare och kabinklass. Den rapporterar även en contrails-kategori (Låg / Medel / Hög) för att visa den icke-CO₂-baserade uppvärmningseffekten från ett specifikt flyg.',
    aboutFlightDistanceTitle: 'Flygruttens avstånd',
    aboutFlightDistance:
      'beräknas lokalt med Haversine-formeln mellan flygplatser, med en omvägsfaktor på 95 km för verkliga rutter. Detta används bara för visning — utsläppssiffran kommer från TIM.',
    aboutCarDistanceTitle: 'Bilruttens avstånd',
    aboutCarDistance:
      'hämtas från OSRM API (Open Source Routing Machine), som returnerar faktisk väglängd och körtid mellan två städer. Utsläppen beräknas sedan med faktorn 0,21 kg CO₂ per km, baserat på en typisk europeisk personbil.',
    aboutTrainTitle: 'Tågjämförelse',
    aboutTrain:
      'använder fågelvägsavståndet mellan städer med en utsläppsfaktor på 0,041 kg CO₂ per km, vilket speglar genomsnittliga europeiska tågutsläpp inklusive elmixen.',
    aboutCompareTitle: 'Jämför dina alternativ',
    aboutCompare:
      'EcoRoute låter dig jämföra utsläppen från ett flyg med bil- och tågalternativ sida vid sida. Använd planeraren för att förstå den verkliga klimatkostnaden för din resa och upptäck sätt att resa med lägre påverkan.',
    accountLoggedOut: 'Du måste vara inloggad för att se din historik.',
    accountLabel: 'Konto',
    accountTitle: 'Min historik',
    accountLoading: 'Laddar historik…',
    accountNoHistory: 'Ingen historik ännu.',
    accountNoHistoryHint:
      'Planera en resa på startsidan så sparas den här automatiskt.',
    accountSavedTrips: '{count} sparade resor',
    accountClearAll: 'Rensa allt',
    accountConfirmClear: 'Är du säker på att du vill rensa hela historiken?',
    accountRemove: 'Ta bort',
    plannerLabel: 'EcoRoute-planerare',
    plannerTitle: 'Flygutsläppsplanerare',
    plannerHideMap: 'Dölj karta',
    plannerShowMap: 'Visa karta',
    plannerFavorites: 'Favoriter',
    plannerLoad: 'Läs in',
    plannerUseCurrentLocationLoading: 'Hämtar plats...',
    plannerUseCurrentLocation: 'Använd nuvarande plats',
    plannerSaveToHistory: 'Spara i historik',
    plannerSaveAsFavorite: 'Spara som favorit',
    plannerGeoUnsupported: 'Geolokalisering stöds inte av den här webbläsaren.',
    plannerGeoLoading: 'Hämtar din nuvarande plats...',
    plannerGeoUsingLocation: 'Använder din nuvarande plats: {city}, {country}',
    plannerGeoDenied: 'Platsåtkomst nekades. Tillåt platsåtkomst för att använda denna funktion.',
    plannerGeoUnavailable: 'Platsinformation är inte tillgänglig.',
    plannerGeoTimeout: 'Platsbegäran tog för lång tid.',
    plannerGeoError: 'Det gick inte att hämta din plats.',
    plannerSavedHistory: 'Flyg sparat i historiken.',
    plannerSavedFavorite: 'Sparat som favorit.',
    cityFrom: 'Från',
    cityTo: 'Till',
    citySearchPlaceholder: 'Sök land, stad eller flygplatskod…',
    citySearchAria: 'Sökning för stad och land för {label}',
    cityTopResults: 'Visar de 50 bästa resultaten. Begränsa din sökning för mer specifika val.',
    cityNoMatches: 'Inga matchande städer hittades.',
    travelCabinClass: 'Kabinklass',
    travelEconomy: 'Ekonomi',
    travelBusiness: 'Business',
    travelFirst: 'Första klass',
    travelNumberOfTravelers: 'Antal resenärer',
    emissionsFetching: 'Hämtar utsläpp från TIM API…',
    emissionsEstimateWarning: 'Live-data är inte tillgänglig — visar uppskattning baserad på standardfaktorer',
    emissionsTitle: 'CO₂-utsläpp',
    emissionsPerPerson: 'Per person:',
    emissionsFlightDistance: 'flygavstånd (inkl. rutt)',
    emissionsDrivingEquivalent: 'med bil',
    emissionsTreesNeeded: 'träd behövs för att kompensera (1 år)',
    emissionsTravelersTotal: 'resenär{suffix} totalt',
    comparisonTitle: 'Transportjämförelse',
    comparisonFlight: 'Flyg',
    comparisonCar: 'Bil',
    comparisonTrain: 'Tåg',
    legsDirectFlight: 'Direktflyg',
    legsFlightRoute: 'Flygrutt · {count} delsträckor',
    flightHistoryEmptyTitle: 'Inga flyg sparade ännu',
    flightHistoryEmptyHint: 'Sök efter ett flyg för att lägga till det i historiken',
    flightHistoryTitle: 'Din flyghistorik ({count})',
    flightHistoryClearAll: 'Rensa hela historiken',
    flightHistoryDelete: 'Ta bort',
    mapHideAirports: 'Dölj flygplatser',
    mapShowAirports: 'Visa flygplatser',
    mapTransferLabel: 'Transfer:',
  },
  es: {
    navbarHome: 'Inicio',
    navbarPlanner: 'Planificador',
    navbarAbout: 'Acerca de',
    navbarHistory: 'Mi historial',
    navbarMenuOpen: 'Abrir menú',
    navbarMenuClose: 'Cerrar menú',
    languageSwitch: 'Idioma',
    authLoading: 'Cargando...',
    authLogIn: 'Iniciar sesión',
    authLogOut: 'Cerrar sesión',
    authSignUp: 'Registrarse',
    loginTabLogIn: 'Iniciar sesión',
    loginTabSignUp: 'Registrarse',
    loginEmail: 'Correo electrónico',
    loginPassword: 'Contraseña',
    loginEmailPlaceholder: 'tu@ejemplo.com',
    loginPasswordPlaceholder: '••••••••',
    loginCancel: 'Cancelar',
    loginError: 'Ocurrió un error',
    landingBadge: 'Planificador de viajes sostenible',
    landingTitleLine1: 'Viaja de forma más inteligente.',
    landingTitleLine2: 'Conoce tu huella de carbono.',
    landingDescription: 'Compara las emisiones de vuelos, trenes y coches en todo el mundo.',
    landingPlanRoute: 'Planifica tu ruta →',
    landingHowItWorks: 'Cómo funciona',
    landingFeaturesTitle: '¿Por qué EcoRoute?',
    landingSaveJourneysTitle: 'Guarda tus viajes',
    landingSaveJourneysDesc: 'Crea una cuenta gratuita para seguir tus rutas, controlar tu huella de carbono con el tiempo y revisar comparaciones anteriores.',
    landingCreateAccount: 'Crear cuenta gratuita',
    landingAlreadyHaveAccount: '¿Ya tienes una cuenta? Inicia sesión',
    landingBottomTitle: '¿Listo para planificar un viaje más ecológico?',
    landingBottomDesc: 'Empieza a comparar rutas y descubre cuánto CO₂ puedes ahorrar.',
    landingOpenPlanner: 'Abrir el planificador →',
    landingFeatureFlightTitle: 'Emisiones de vuelo',
    landingFeatureFlightDesc: 'Calcula la emisión exacta de CO₂ por vuelo usando metodología certificada por la OACI, multiplicadores por clase y RFI.',
    landingFeatureAlternativesTitle: 'Alternativas más ecológicas',
    landingFeatureAlternativesDesc: 'Descubre rutas en tren y multimodales con menores emisiones por Europa como alternativa al avión.',
    landingFeatureCompareTitle: 'Comparación lado a lado',
    landingFeatureCompareDesc: 'Ve vuelos y alternativas juntos — emisiones, distancia e impacto ecológico de un vistazo.',
    landingFeatureHistoryTitle: 'Historial de viajes',
    landingFeatureHistoryDesc: 'Inicia sesión para guardar rutas, seguir tu huella total de carbono y monitorizar tus hábitos de viaje.',
    aboutBadge: 'Acerca de',
    aboutTitle: 'Acerca de EcoRoute',
    aboutIntro: 'EcoRoute es un proyecto estudiantil diseñado para hacer visibles y comparables las emisiones de viaje. Creemos que las decisiones informadas impulsan el cambio — conocer el impacto ambiental de tu viaje te ayuda a tomar decisiones alineadas con tus valores.',
    aboutMissionTitle: 'Nuestra misión',
    aboutMission: 'Trabajamos hacia el Objetivo de Desarrollo Sostenible 13 de la ONU (acción por el clima) proporcionando datos de emisiones accesibles y precisos para vuelos y viajes terrestres. En lugar de estimar nosotros mismos, confiamos en fuentes externas autorizadas para que las cifras sean lo más fiables posible.',
    aboutHowItWorksTitle: 'Cómo funciona',
    aboutFlightEmissionsTitle: 'Emisiones de vuelo — Google Travel Impact Model (TIM)',
    aboutFlightEmissions: 'Todas las cifras de CO₂ de vuelo provienen de la API Travel Impact Model de Google. TIM es un modelo de código abierto que usa tipos reales de aeronaves, configuraciones de asientos, factores de ocupación y datos de rutas para estimar emisiones por pasajero según la clase. También informa una categoría de estelas (baja / moderada / alta) para indicar la contribución no-CO₂ al calentamiento de un vuelo concreto.',
    aboutFlightDistanceTitle: 'Distancia de la ruta aérea',
    aboutFlightDistance: 'se calcula localmente usando la fórmula de Haversine entre aeropuertos, con un factor de desvío de 95 km para rutas reales. Esto solo se usa para mostrar información — la cifra de emisiones proviene de TIM.',
    aboutCarDistanceTitle: 'Distancia de la ruta en coche',
    aboutCarDistance: 'se obtiene de la API OSRM (Open Source Routing Machine), que devuelve la distancia real por carretera y el tiempo de conducción entre dos ciudades. Después, las emisiones se calculan aplicando un factor de 0,21 kg de CO₂ por km, basado en un coche europeo típico.',
    aboutTrainTitle: 'Comparación con tren',
    aboutTrain: 'usa la distancia en línea recta entre ciudades con un factor de emisión de 0,041 kg de CO₂ por km, reflejando las emisiones medias del ferrocarril europeo incluyendo la mezcla eléctrica.',
    aboutCompareTitle: 'Compara tus opciones',
    aboutCompare: 'EcoRoute te permite comparar las emisiones de un vuelo con alternativas en coche y tren lado a lado. Usa el planificador para entender el verdadero coste climático de tu viaje y descubrir formas de viajar con menor impacto.',
    accountLoggedOut: 'Debes iniciar sesión para ver tu historial.',
    accountLabel: 'Cuenta',
    accountTitle: 'Mi historial',
    accountLoading: 'Cargando historial…',
    accountNoHistory: 'Aún no hay historial.',
    accountNoHistoryHint: 'Planifica un viaje en la página principal y se guardará aquí automáticamente.',
    accountSavedTrips: '{count} viajes guardados',
    accountClearAll: 'Borrar todo',
    accountConfirmClear: '¿Seguro que quieres borrar todo el historial?',
    accountRemove: 'Eliminar',
    plannerLabel: 'Planificador EcoRoute',
    plannerTitle: 'Planificador de emisiones de vuelos',
    plannerHideMap: 'Ocultar mapa',
    plannerShowMap: 'Mostrar mapa',
    plannerFavorites: 'Favoritos',
    plannerLoad: 'Cargar',
    plannerUseCurrentLocationLoading: 'Obteniendo ubicación...',
    plannerUseCurrentLocation: 'Usar ubicación actual',
    plannerSaveToHistory: 'Guardar en historial',
    plannerSaveAsFavorite: 'Guardar como favorito',
    plannerGeoUnsupported: 'La geolocalización no es compatible con este navegador.',
    plannerGeoLoading: 'Obteniendo tu ubicación actual...',
    plannerGeoUsingLocation: 'Usando tu ubicación actual: {city}, {country}',
    plannerGeoDenied: 'Acceso a la ubicación denegado. Permite el acceso para usar esta función.',
    plannerGeoUnavailable: 'La información de ubicación no está disponible.',
    plannerGeoTimeout: 'La solicitud de ubicación agotó el tiempo.',
    plannerGeoError: 'No se pudo obtener tu ubicación.',
    plannerSavedHistory: 'Vuelo guardado en el historial.',
    plannerSavedFavorite: 'Guardado como favorito.',
    cityFrom: 'Desde',
    cityTo: 'Hasta',
    citySearchPlaceholder: 'Buscar país, ciudad o código de aeropuerto…',
    citySearchAria: 'Búsqueda de ciudad y país para {label}',
    cityTopResults: 'Mostrando los 50 mejores resultados. Afina tu búsqueda para opciones más específicas.',
    cityNoMatches: 'No se encontraron ciudades que coincidan.',
    travelCabinClass: 'Clase de cabina',
    travelEconomy: 'Turista',
    travelBusiness: 'Business',
    travelFirst: 'Primera',
    travelNumberOfTravelers: 'Número de viajeros',
    emissionsFetching: 'Obteniendo emisiones de la API TIM…',
    emissionsEstimateWarning: 'Datos en vivo no disponibles — se muestra una estimación basada en factores estándar',
    emissionsTitle: 'Emisiones de CO₂',
    emissionsPerPerson: 'Por persona:',
    emissionsFlightDistance: 'distancia de vuelo (incl. ruta)',
    emissionsDrivingEquivalent: 'en coche',
    emissionsTreesNeeded: 'árbol{suffix} necesario para compensar (1 año)',
    emissionsTravelersTotal: 'viajero{suffix} total',
    comparisonTitle: 'Comparación de modos',
    comparisonFlight: 'Vuelo',
    comparisonCar: 'Coche',
    comparisonTrain: 'Tren',
    legsDirectFlight: 'Vuelo directo',
    legsFlightRoute: 'Ruta de vuelo · {count} tramos',
    flightHistoryEmptyTitle: 'Aún no hay vuelos guardados',
    flightHistoryEmptyHint: 'Busca un vuelo para añadirlo a tu historial',
    flightHistoryTitle: 'Tu historial de vuelos ({count})',
    flightHistoryClearAll: 'Borrar todo el historial',
    flightHistoryDelete: 'Eliminar',
    mapHideAirports: 'Ocultar aeropuertos',
    mapShowAirports: 'Mostrar aeropuertos',
    mapTransferLabel: 'Transferencia:',
  },
  fr: {
    navbarHome: 'Accueil',
    navbarPlanner: 'Planificateur',
    navbarAbout: 'À propos',
    navbarHistory: 'Mon historique',
    navbarMenuOpen: 'Ouvrir le menu',
    navbarMenuClose: 'Fermer le menu',
    languageSwitch: 'Langue',
    authLoading: 'Chargement...',
    authLogIn: 'Se connecter',
    authLogOut: 'Se déconnecter',
    authSignUp: 'S’inscrire',
    loginTabLogIn: 'Se connecter',
    loginTabSignUp: 'S’inscrire',
    loginEmail: 'E-mail',
    loginPassword: 'Mot de passe',
    loginEmailPlaceholder: 'vous@exemple.com',
    loginPasswordPlaceholder: '••••••••',
    loginCancel: 'Annuler',
    loginError: 'Une erreur est survenue',
    landingBadge: 'Planificateur de voyage durable',
    landingTitleLine1: 'Voyagez plus intelligemment.',
    landingTitleLine2: 'Connaissez votre empreinte carbone.',
    landingDescription: 'Comparez les émissions des vols, trains et voitures dans le monde entier.',
    landingPlanRoute: 'Planifier votre trajet →',
    landingHowItWorks: 'Comment ça marche',
    landingFeaturesTitle: 'Pourquoi EcoRoute ?',
    landingSaveJourneysTitle: 'Enregistrez vos trajets',
    landingSaveJourneysDesc:
      'Créez un compte gratuit pour suivre vos itinéraires, surveiller votre empreinte carbone au fil du temps et revoir les comparaisons passées.',
    landingCreateAccount: 'Créer un compte gratuit',
    landingAlreadyHaveAccount: 'Vous avez déjà un compte ? Connectez-vous',
    landingBottomTitle: 'Prêt à planifier un voyage plus vert ?',
    landingBottomDesc: 'Commencez à comparer les trajets et découvrez combien de CO₂ vous pouvez économiser.',
    landingOpenPlanner: 'Ouvrir le planificateur →',
    landingFeatureFlightTitle: 'Émissions des vols',
    landingFeatureFlightDesc:
      'Calculez précisément les émissions de CO₂ par vol grâce à la méthodologie certifiée ICAO, aux multiplicateurs par classe et au RFI.',
    landingFeatureAlternativesTitle: 'Alternatives plus vertes',
    landingFeatureAlternativesDesc:
      'Découvrez des trajets en train et multimodaux à plus faibles émissions en Europe comme alternative à l’avion.',
    landingFeatureCompareTitle: 'Comparaison côte à côte',
    landingFeatureCompareDesc:
      'Voyez les vols et les alternatives ensemble — émissions, distance et impact écologique en un coup d’œil.',
    landingFeatureHistoryTitle: 'Historique des trajets',
    landingFeatureHistoryDesc:
      'Connectez-vous pour enregistrer des trajets, suivre votre empreinte carbone totale et surveiller vos habitudes de déplacement.',
    aboutBadge: 'À propos',
    aboutTitle: 'À propos d’EcoRoute',
    aboutIntro:
      'EcoRoute est un projet étudiant conçu pour rendre les émissions de voyage visibles et comparables. Nous pensons que des choix éclairés favorisent le changement — connaître l’impact environnemental de votre trajet vous aide à prendre des décisions alignées avec vos valeurs.',
    aboutMissionTitle: 'Notre mission',
    aboutMission:
      'Nous travaillons vers l’objectif de développement durable 13 de l’ONU (lutte contre le changement climatique) en fournissant des données d’émissions accessibles et précises pour les trajets aériens et terrestres. Plutôt que d’estimer nous-mêmes, nous nous appuyons sur des sources externes autorisées pour que les chiffres soient aussi fiables que possible.',
    aboutHowItWorksTitle: 'Comment ça marche',
    aboutFlightEmissionsTitle: 'Émissions des vols — Google Travel Impact Model (TIM)',
    aboutFlightEmissions:
      'Toutes les valeurs de CO₂ des vols proviennent de l’API Travel Impact Model de Google. TIM est un modèle open source qui utilise de vrais types d’avions, configurations de sièges, facteurs de remplissage et données de routage pour estimer les émissions par passager selon la classe. Il indique aussi une catégorie de traînées (faible / modérée / élevée) pour signaler la contribution au réchauffement hors CO₂ d’un vol précis.',
    aboutFlightDistanceTitle: 'Distance de la route aérienne',
    aboutFlightDistance:
      'est calculée localement avec la formule de Haversine entre les aéroports, avec un facteur de détour de 95 km ajouté pour les trajets réels. Cela ne sert qu’à l’affichage — la valeur des émissions provient de TIM.',
    aboutCarDistanceTitle: 'Distance de la route en voiture',
    aboutCarDistance:
      'est récupérée depuis l’API OSRM (Open Source Routing Machine), qui renvoie la distance routière réelle et le temps de conduite entre deux villes. Les émissions sont ensuite calculées avec un facteur de 0,21 kg de CO₂ par km, basé sur une voiture particulière européenne typique.',
    aboutTrainTitle: 'Comparaison avec le train',
    aboutTrain:
      'utilise la distance en ligne droite entre les villes avec un facteur d’émission de 0,041 kg de CO₂ par km, reflétant les émissions moyennes du rail européen, mix électrique inclus.',
    aboutCompareTitle: 'Comparez vos options',
    aboutCompare:
      'EcoRoute vous permet de comparer les émissions d’un vol avec des alternatives en voiture et en train côte à côte. Utilisez le planificateur pour comprendre le vrai coût climatique de votre trajet et découvrir des moyens de voyager à plus faible impact.',
    accountLoggedOut: 'Vous devez être connecté pour voir votre historique.',
    accountLabel: 'Compte',
    accountTitle: 'Mon historique',
    accountLoading: 'Chargement de l’historique…',
    accountNoHistory: 'Aucun historique pour le moment.',
    accountNoHistoryHint:
      'Planifiez un trajet sur la page d’accueil et il sera enregistré ici automatiquement.',
    accountSavedTrips: '{count} trajets enregistrés',
    accountClearAll: 'Effacer tout l’historique',
    accountConfirmClear: 'Voulez-vous vraiment effacer tout l’historique ?',
    accountRemove: 'Supprimer',
    plannerLabel: 'Planificateur EcoRoute',
    plannerTitle: 'Planificateur d’émissions de vols',
    plannerHideMap: 'Masquer la carte',
    plannerShowMap: 'Afficher la carte',
    plannerFavorites: 'Favoris',
    plannerLoad: 'Charger',
    plannerUseCurrentLocationLoading: 'Obtention de la localisation...',
    plannerUseCurrentLocation: 'Utiliser la localisation actuelle',
    plannerSaveToHistory: 'Enregistrer dans l’historique',
    plannerSaveAsFavorite: 'Enregistrer en favori',
    plannerGeoUnsupported: 'La géolocalisation n’est pas prise en charge par ce navigateur.',
    plannerGeoLoading: 'Obtention de votre localisation actuelle...',
    plannerGeoUsingLocation: 'Utilisation de votre localisation actuelle : {city}, {country}',
    plannerGeoDenied: 'Accès à la localisation refusé. Autorisez l’accès pour utiliser cette fonction.',
    plannerGeoUnavailable: 'Les informations de localisation ne sont pas disponibles.',
    plannerGeoTimeout: 'La demande de localisation a expiré.',
    plannerGeoError: 'Impossible d’obtenir votre localisation.',
    plannerSavedHistory: 'Vol enregistré dans l’historique.',
    plannerSavedFavorite: 'Enregistré comme favori.',
    cityFrom: 'De',
    cityTo: 'À',
    citySearchPlaceholder: 'Rechercher un pays, une ville ou un code aéroport…',
    citySearchAria: 'Recherche ville et pays pour {label}',
    cityTopResults: 'Affichage des 50 meilleurs résultats. Affinez votre recherche pour des choix plus précis.',
    cityNoMatches: 'Aucune ville correspondante trouvée.',
    travelCabinClass: 'Classe de cabine',
    travelEconomy: 'Économie',
    travelBusiness: 'Affaires',
    travelFirst: 'Première',
    travelNumberOfTravelers: 'Nombre de voyageurs',
    emissionsFetching: 'Récupération des émissions depuis l’API TIM…',
    emissionsEstimateWarning: 'Données en direct indisponibles — estimation affichée à partir de facteurs standard',
    emissionsTitle: 'Émissions de CO₂',
    emissionsPerPerson: 'Par personne :',
    emissionsFlightDistance: 'distance de vol (trajet inclus)',
    emissionsDrivingEquivalent: 'en voiture',
    emissionsTreesNeeded: 'arbre{suffix} nécessaire pour compenser (1 an)',
    emissionsTravelersTotal: 'voyageur{suffix} total',
    comparisonTitle: 'Comparaison des modes',
    comparisonFlight: 'Vol',
    comparisonCar: 'Voiture',
    comparisonTrain: 'Train',
    legsDirectFlight: 'Vol direct',
    legsFlightRoute: 'Itinéraire aérien · {count} segments',
    flightHistoryEmptyTitle: 'Aucun vol enregistré pour le moment',
    flightHistoryEmptyHint: 'Recherchez un vol pour l’ajouter à votre historique',
    flightHistoryTitle: 'Votre historique de vols ({count})',
    flightHistoryClearAll: 'Effacer tout l’historique',
    flightHistoryDelete: 'Supprimer',
    mapHideAirports: 'Masquer les aéroports',
    mapShowAirports: 'Afficher les aéroports',
    mapTransferLabel: 'Correspondance :',
  },
  de: {
    navbarHome: 'Start',
    navbarPlanner: 'Planer',
    navbarAbout: 'Über uns',
    navbarHistory: 'Mein Verlauf',
    navbarMenuOpen: 'Menü öffnen',
    navbarMenuClose: 'Menü schließen',
    languageSwitch: 'Sprache',
    authLoading: 'Laden...',
    authLogIn: 'Anmelden',
    authLogOut: 'Abmelden',
    authSignUp: 'Registrieren',
    loginTabLogIn: 'Anmelden',
    loginTabSignUp: 'Registrieren',
    loginEmail: 'E-Mail',
    loginPassword: 'Passwort',
    loginEmailPlaceholder: 'du@beispiel.de',
    loginPasswordPlaceholder: '••••••••',
    loginCancel: 'Abbrechen',
    loginError: 'Ein Fehler ist aufgetreten',
    landingBadge: 'Nachhaltiger Reiseplaner',
    landingTitleLine1: 'Reise smarter.',
    landingTitleLine2: 'Kennt deinen CO₂-Fußabdruck.',
    landingDescription: 'Vergleiche Emissionen von Flügen, Zügen und Autos weltweit.',
    landingPlanRoute: 'Route planen →',
    landingHowItWorks: 'So funktioniert es',
    landingFeaturesTitle: 'Warum EcoRoute?',
    landingSaveJourneysTitle: 'Reisen speichern',
    landingSaveJourneysDesc:
      'Erstelle ein kostenloses Konto, um deine Routen zu verfolgen, deinen CO₂-Fußabdruck über die Zeit zu beobachten und frühere Vergleiche erneut anzusehen.',
    landingCreateAccount: 'Kostenloses Konto erstellen',
    landingAlreadyHaveAccount: 'Schon ein Konto? Anmelden',
    landingBottomTitle: 'Bereit für eine grünere Reise?',
    landingBottomDesc: 'Vergleiche Routen und entdecke, wie viel CO₂ du sparen kannst.',
    landingOpenPlanner: 'Planer öffnen →',
    landingFeatureFlightTitle: 'Flugemissionen',
    landingFeatureFlightDesc:
      'Berechne den exakten CO₂-Ausstoß pro Flug mit ICAO-zertifizierter Methodik, Kabinenklassen-Multiplikatoren und RFI.',
    landingFeatureAlternativesTitle: 'Grünere Alternativen',
    landingFeatureAlternativesDesc:
      'Entdecke emissionsärmere Zug- und Multimodalrouten durch Europa als Alternative zum Fliegen.',
    landingFeatureCompareTitle: 'Direkter Vergleich',
    landingFeatureCompareDesc:
      'Sieh Flüge und Alternativen zusammen — Emissionen, Entfernung und Klimaauswirkung auf einen Blick.',
    landingFeatureHistoryTitle: 'Reiseverlauf',
    landingFeatureHistoryDesc:
      'Melde dich an, um Routen zu speichern, deinen gesamten CO₂-Fußabdruck zu verfolgen und Reisegewohnheiten zu beobachten.',
    aboutBadge: 'Über',
    aboutTitle: 'Über EcoRoute',
    aboutIntro:
      'EcoRoute ist ein Studentenprojekt, das Reiseemissionen sichtbar und vergleichbar macht. Wir glauben, dass informierte Entscheidungen Wandel fördern — das Wissen um die Umweltwirkung deiner Reise hilft dir, Entscheidungen im Einklang mit deinen Werten zu treffen.',
    aboutMissionTitle: 'Unsere Mission',
    aboutMission:
      'Wir arbeiten auf das UN-Nachhaltigkeitsziel 13 (Klimaschutz) hin, indem wir zugängliche und genaue Emissionsdaten für Flug- und Landverkehr bereitstellen. Statt Emissionen selbst zu schätzen, verlassen wir uns auf autoritative externe Datenquellen, damit die Zahlen möglichst verlässlich sind.',
    aboutHowItWorksTitle: 'So funktioniert es',
    aboutFlightEmissionsTitle: 'Flugemissionen — Google Travel Impact Model (TIM)',
    aboutFlightEmissions:
      'Alle Flug-CO₂-Werte stammen aus der Google Travel Impact Model API. TIM ist ein Open-Source-Modell, das reale Flugzeugtypen, Sitzkonfigurationen, Auslastung und Routendaten nutzt, um Emissionen pro Passagier nach Kabinenklasse zu schätzen. Es berichtet außerdem eine Kondensstreifen-Kategorie (niedrig / mittel / hoch), um den nicht-CO₂-bedingten Erwärmungsbeitrag eines bestimmten Fluges anzuzeigen.',
    aboutFlightDistanceTitle: 'Flugstrecke',
    aboutFlightDistance:
      'wird lokal mit der Haversine-Formel zwischen Flughäfen berechnet, mit einem Umwegfaktor von 95 km für reale Routen. Das dient nur zur Anzeige — der Emissionswert selbst stammt von TIM.',
    aboutCarDistanceTitle: 'Autostrecke',
    aboutCarDistance:
      'wird von der OSRM API (Open Source Routing Machine) abgerufen, die die tatsächliche Straßenentfernung und Fahrzeit zwischen zwei Städten liefert. Die Emissionen werden dann mit einem Faktor von 0,21 kg CO₂ pro km berechnet, basierend auf einem typischen europäischen Pkw.',
    aboutTrainTitle: 'Zugvergleich',
    aboutTrain:
      'verwendet die Luftlinienentfernung zwischen Städten mit einem Emissionsfaktor von 0,041 kg CO₂ pro km und spiegelt durchschnittliche europäische Bahnemissionen inklusive Strommix wider.',
    aboutCompareTitle: 'Vergleiche deine Optionen',
    aboutCompare:
      'EcoRoute ermöglicht dir den Vergleich von Flugemissionen mit Auto- und Zugalternativen nebeneinander. Nutze den Planer, um die wahre Klimawirkung deiner Reise zu verstehen und Wege mit geringerer Auswirkung zu entdecken.',
    accountLoggedOut: 'Du musst angemeldet sein, um deinen Verlauf zu sehen.',
    accountLabel: 'Konto',
    accountTitle: 'Mein Verlauf',
    accountLoading: 'Verlauf wird geladen…',
    accountNoHistory: 'Noch kein Verlauf.',
    accountNoHistoryHint:
      'Plane eine Reise auf der Startseite, dann wird sie hier automatisch gespeichert.',
    accountSavedTrips: '{count} gespeicherte Reisen',
    accountClearAll: 'Alles löschen',
    accountConfirmClear: 'Möchtest du wirklich den gesamten Verlauf löschen?',
    accountRemove: 'Entfernen',
    plannerLabel: 'EcoRoute-Planer',
    plannerTitle: 'Flugemissions-Planer',
    plannerHideMap: 'Karte ausblenden',
    plannerShowMap: 'Karte anzeigen',
    plannerFavorites: 'Favoriten',
    plannerLoad: 'Laden',
    plannerUseCurrentLocationLoading: 'Standort wird ermittelt...',
    plannerUseCurrentLocation: 'Aktuellen Standort verwenden',
    plannerSaveToHistory: 'In Verlauf speichern',
    plannerSaveAsFavorite: 'Als Favorit speichern',
    plannerGeoUnsupported: 'Geolokalisierung wird von diesem Browser nicht unterstützt.',
    plannerGeoLoading: 'Deinen aktuellen Standort wird ermittelt...',
    plannerGeoUsingLocation: 'Aktueller Standort wird verwendet: {city}, {country}',
    plannerGeoDenied: 'Standortzugriff verweigert. Bitte erlauben, um diese Funktion zu nutzen.',
    plannerGeoUnavailable: 'Standortinformationen sind nicht verfügbar.',
    plannerGeoTimeout: 'Standortanfrage hat zu lange gedauert.',
    plannerGeoError: 'Dein Standort konnte nicht ermittelt werden.',
    plannerSavedHistory: 'Flug im Verlauf gespeichert.',
    plannerSavedFavorite: 'Als Favorit gespeichert.',
    cityFrom: 'Von',
    cityTo: 'Nach',
    citySearchPlaceholder: 'Land, Stadt oder Flughafencode suchen…',
    citySearchAria: 'Stadt- und Ländersuche für {label}',
    cityTopResults: 'Es werden die 50 besten Ergebnisse angezeigt. Verfeinere die Suche für genauere Treffer.',
    cityNoMatches: 'Keine passenden Städte gefunden.',
    travelCabinClass: 'Kabinenklasse',
    travelEconomy: 'Economy',
    travelBusiness: 'Business',
    travelFirst: 'First',
    travelNumberOfTravelers: 'Anzahl der Reisenden',
    emissionsFetching: 'Emissionen werden von der TIM-API abgerufen…',
    emissionsEstimateWarning: 'Live-Daten nicht verfügbar — Schätzung auf Basis standardisierter Emissionsfaktoren',
    emissionsTitle: 'CO₂-Emissionen',
    emissionsPerPerson: 'Pro Person:',
    emissionsFlightDistance: 'Flugdistanz (inkl. Route)',
    emissionsDrivingEquivalent: 'mit dem Auto',
    emissionsTreesNeeded: 'Baum{suffix} benötigt zum Ausgleich (1 Jahr)',
    emissionsTravelersTotal: 'Reisende{suffix} gesamt',
    comparisonTitle: 'Verkehrsmittelvergleich',
    comparisonFlight: 'Flug',
    comparisonCar: 'Auto',
    comparisonTrain: 'Zug',
    legsDirectFlight: 'Direktflug',
    legsFlightRoute: 'Flugroute · {count} Segmente',
    flightHistoryEmptyTitle: 'Noch keine Flüge gespeichert',
    flightHistoryEmptyHint: 'Suche nach einem Flug, um ihn zur Historie hinzuzufügen',
    flightHistoryTitle: 'Dein Flugverlauf ({count})',
    flightHistoryClearAll: 'Gesamten Verlauf löschen',
    flightHistoryDelete: 'Löschen',
    mapHideAirports: 'Flughäfen ausblenden',
    mapShowAirports: 'Flughäfen anzeigen',
    mapTransferLabel: 'Umstieg:',
  },
  it: {
    navbarHome: 'Home',
    navbarPlanner: 'Pianificatore',
    navbarAbout: 'Informazioni',
    navbarHistory: 'La mia cronologia',
    navbarMenuOpen: 'Apri menu',
    navbarMenuClose: 'Chiudi menu',
    languageSwitch: 'Lingua',
    authLoading: 'Caricamento...',
    authLogIn: 'Accedi',
    authLogOut: 'Esci',
    authSignUp: 'Registrati',
    loginTabLogIn: 'Accedi',
    loginTabSignUp: 'Registrati',
    loginEmail: 'Email',
    loginPassword: 'Password',
    loginEmailPlaceholder: 'tuo@esempio.com',
    loginPasswordPlaceholder: '••••••••',
    loginCancel: 'Annulla',
    loginError: 'Si è verificato un errore',
    landingBadge: 'Pianificatore di viaggi sostenibili',
    landingTitleLine1: 'Viaggia in modo più intelligente.',
    landingTitleLine2: 'Conosci la tua impronta di carbonio.',
    landingDescription: 'Confronta le emissioni di voli, treni e auto in tutto il mondo.',
    landingPlanRoute: 'Pianifica il tuo itinerario →',
    landingHowItWorks: 'Come funziona',
    landingFeaturesTitle: 'Perché EcoRoute?',
    landingSaveJourneysTitle: 'Salva i tuoi viaggi',
    landingSaveJourneysDesc:
      'Crea un account gratuito per seguire i tuoi itinerari, monitorare nel tempo la tua impronta di carbonio e rivedere i confronti passati.',
    landingCreateAccount: 'Crea account gratuito',
    landingAlreadyHaveAccount: 'Hai già un account? Accedi',
    landingBottomTitle: 'Pronto a pianificare un viaggio più verde?',
    landingBottomDesc: 'Inizia a confrontare gli itinerari e scopri quanto CO₂ puoi risparmiare.',
    landingOpenPlanner: 'Apri il pianificatore →',
    landingFeatureFlightTitle: 'Emissioni dei voli',
    landingFeatureFlightDesc:
      'Calcola l’esatta emissione di CO₂ per volo usando una metodologia certificata ICAO, moltiplicatori per classe di cabina e RFI.',
    landingFeatureAlternativesTitle: 'Alternative più verdi',
    landingFeatureAlternativesDesc:
      'Scopri percorsi in treno e multimodali a minori emissioni in Europa come alternativa al volo.',
    landingFeatureCompareTitle: 'Confronto affiancato',
    landingFeatureCompareDesc:
      'Vedi voli e alternative insieme — emissioni, distanza e impatto ecologico a colpo d’occhio.',
    landingFeatureHistoryTitle: 'Cronologia dei viaggi',
    landingFeatureHistoryDesc:
      'Accedi per salvare gli itinerari, monitorare la tua impronta totale e seguire le abitudini di viaggio nel tempo.',
    aboutBadge: 'Informazioni',
    aboutTitle: 'Informazioni su EcoRoute',
    aboutIntro:
      'EcoRoute è un progetto studentesco progettato per rendere visibili e confrontabili le emissioni di viaggio. Crediamo che le scelte consapevoli favoriscano il cambiamento — conoscere l’impatto ambientale del tuo viaggio ti aiuta a prendere decisioni in linea con i tuoi valori.',
    aboutMissionTitle: 'La nostra missione',
    aboutMission:
      'Lavoriamo verso l’Obiettivo di Sviluppo Sostenibile 13 dell’ONU (azione per il clima) fornendo dati sulle emissioni accessibili e accurati per voli e spostamenti terrestri. Invece di stimarle noi stessi, ci affidiamo a fonti esterne autorevoli affinché i numeri siano il più affidabili possibile.',
    aboutHowItWorksTitle: 'Come funziona',
    aboutFlightEmissionsTitle: 'Emissioni dei voli — Google Travel Impact Model (TIM)',
    aboutFlightEmissions:
      'Tutti i valori di CO₂ dei voli provengono dall’API Travel Impact Model di Google. TIM è un modello open source che usa tipi reali di aeromobili, configurazioni dei sedili, fattori di riempimento e dati di routing per stimare le emissioni per passeggero in base alla classe. Riporta anche una categoria di scie di condensazione (bassa / moderata / alta) per indicare il contributo al riscaldamento non-CO₂ di un volo specifico.',
    aboutFlightDistanceTitle: 'Distanza della rotta aerea',
    aboutFlightDistance:
      'viene calcolata localmente usando la formula di Haversine tra aeroporti, con un fattore di deviazione di 95 km per i percorsi reali. Questo serve solo per la visualizzazione — il dato di emissione proviene da TIM.',
    aboutCarDistanceTitle: 'Distanza della rotta in auto',
    aboutCarDistance:
      'viene ottenuta dall’API OSRM (Open Source Routing Machine), che restituisce la distanza stradale reale e il tempo di guida tra due città. Le emissioni vengono quindi calcolate applicando un fattore di 0,21 kg di CO₂ per km, basato su una tipica auto passeggeri europea.',
    aboutTrainTitle: 'Confronto con il treno',
    aboutTrain:
      'usa la distanza in linea d’aria tra le città con un fattore di emissione di 0,041 kg di CO₂ per km, riflettendo le emissioni medie ferroviarie europee incluso il mix elettrico.',
    aboutCompareTitle: 'Confronta le tue opzioni',
    aboutCompare:
      'EcoRoute ti consente di confrontare le emissioni di un volo con le alternative in auto e in treno affiancate. Usa il pianificatore per capire il vero costo climatico del tuo viaggio e scoprire modi di viaggiare a impatto minore.',
    accountLoggedOut: 'Devi accedere per visualizzare la tua cronologia.',
    accountLabel: 'Account',
    accountTitle: 'La mia cronologia',
    accountLoading: 'Caricamento cronologia…',
    accountNoHistory: 'Nessuna cronologia ancora.',
    accountNoHistoryHint:
      'Pianifica un viaggio nella pagina principale e verrà salvato qui automaticamente.',
    accountSavedTrips: '{count} viaggi salvati',
    accountClearAll: 'Cancella tutto',
    accountConfirmClear: 'Sei sicuro di voler cancellare tutta la cronologia?',
    accountRemove: 'Rimuovi',
    plannerLabel: 'Pianificatore EcoRoute',
    plannerTitle: 'Pianificatore emissioni voli',
    plannerHideMap: 'Nascondi mappa',
    plannerShowMap: 'Mostra mappa',
    plannerFavorites: 'Preferiti',
    plannerLoad: 'Carica',
    plannerUseCurrentLocationLoading: 'Recupero posizione...',
    plannerUseCurrentLocation: 'Usa posizione attuale',
    plannerSaveToHistory: 'Salva nella cronologia',
    plannerSaveAsFavorite: 'Salva come preferito',
    plannerGeoUnsupported: 'La geolocalizzazione non è supportata da questo browser.',
    plannerGeoLoading: 'Recupero della tua posizione attuale...',
    plannerGeoUsingLocation: 'Uso della tua posizione attuale: {city}, {country}',
    plannerGeoDenied: 'Accesso alla posizione negato. Consenti l’accesso per usare questa funzione.',
    plannerGeoUnavailable: 'Le informazioni sulla posizione non sono disponibili.',
    plannerGeoTimeout: 'La richiesta di posizione è scaduta.',
    plannerGeoError: 'Impossibile ottenere la tua posizione.',
    plannerSavedHistory: 'Volo salvato nella cronologia.',
    plannerSavedFavorite: 'Salvato come preferito.',
    cityFrom: 'Da',
    cityTo: 'A',
    citySearchPlaceholder: 'Cerca paese, città o codice aeroporto…',
    citySearchAria: 'Ricerca città e paese per {label}',
    cityTopResults: 'Visualizzazione dei primi 50 risultati. Raffina la ricerca per scelte più specifiche.',
    cityNoMatches: 'Nessuna città corrispondente trovata.',
    travelCabinClass: 'Classe di cabina',
    travelEconomy: 'Economy',
    travelBusiness: 'Business',
    travelFirst: 'Prima',
    travelNumberOfTravelers: 'Numero di viaggiatori',
    emissionsFetching: 'Recupero emissioni dall’API TIM…',
    emissionsEstimateWarning: 'Dati live non disponibili — viene mostrata una stima basata su fattori standard',
    emissionsTitle: 'Emissioni di CO₂',
    emissionsPerPerson: 'Per persona:',
    emissionsFlightDistance: 'distanza del volo (incluso routing)',
    emissionsDrivingEquivalent: 'in auto',
    emissionsTreesNeeded: 'alber{suffix} necessari per compensare (1 anno)',
    emissionsTravelersTotal: 'viaggiator{suffix} totale',
    comparisonTitle: 'Confronto modalità',
    comparisonFlight: 'Volo',
    comparisonCar: 'Auto',
    comparisonTrain: 'Treno',
    legsDirectFlight: 'Volo diretto',
    legsFlightRoute: 'Rotta del volo · {count} tratte',
    flightHistoryEmptyTitle: 'Nessun volo salvato ancora',
    flightHistoryEmptyHint: 'Cerca un volo per aggiungerlo alla cronologia',
    flightHistoryTitle: 'La tua cronologia voli ({count})',
    flightHistoryClearAll: 'Cancella tutta la cronologia',
    flightHistoryDelete: 'Elimina',
    mapHideAirports: 'Nascondi aeroporti',
    mapShowAirports: 'Mostra aeroporti',
    mapTransferLabel: 'Scalo:',
  },
  ru: {
    navbarHome: 'Главная',
    navbarPlanner: 'Планировщик',
    navbarAbout: 'О проекте',
    navbarHistory: 'Моя история',
    navbarMenuOpen: 'Открыть меню',
    navbarMenuClose: 'Закрыть меню',
    languageSwitch: 'Язык',
    authLoading: 'Загрузка...',
    authLogIn: 'Войти',
    authLogOut: 'Выйти',
    authSignUp: 'Зарегистрироваться',
    loginTabLogIn: 'Войти',
    loginTabSignUp: 'Зарегистрироваться',
    loginEmail: 'Электронная почта',
    loginPassword: 'Пароль',
    loginEmailPlaceholder: 'you@example.com',
    loginPasswordPlaceholder: '••••••••',
    loginCancel: 'Отмена',
    loginError: 'Произошла ошибка',
    landingBadge: 'Планировщик устойчивых поездок',
    landingTitleLine1: 'Путешествуйте умнее.',
    landingTitleLine2: 'Знайте свой углеродный след.',
    landingDescription: 'Сравнивайте выбросы авиаперелётов, поездов и автомобилей по всему миру.',
    landingPlanRoute: 'Спланировать маршрут →',
    landingHowItWorks: 'Как это работает',
    landingFeaturesTitle: 'Почему EcoRoute?',
    landingSaveJourneysTitle: 'Сохраняйте поездки',
    landingSaveJourneysDesc:
      'Создайте бесплатный аккаунт, чтобы отслеживать маршруты, следить за углеродным следом со временем и пересматривать прошлые сравнения.',
    landingCreateAccount: 'Создать бесплатный аккаунт',
    landingAlreadyHaveAccount: 'Уже есть аккаунт? Войти',
    landingBottomTitle: 'Готовы спланировать более экологичную поездку?',
    landingBottomDesc: 'Начните сравнивать маршруты и узнайте, сколько CO₂ можно сэкономить.',
    landingOpenPlanner: 'Открыть планировщик →',
    landingFeatureFlightTitle: 'Выбросы авиарейсов',
    landingFeatureFlightDesc:
      'Рассчитывайте точный выброс CO₂ на рейс с помощью методологии ICAO, коэффициентов класса салона и RFI.',
    landingFeatureAlternativesTitle: 'Более экологичные альтернативы',
    landingFeatureAlternativesDesc:
      'Откройте для себя маршруты на поезде и мультимодальные маршруты с меньшими выбросами по Европе как альтернативу полёту.',
    landingFeatureCompareTitle: 'Сравнение рядом',
    landingFeatureCompareDesc:
      'Смотрите рейсы и альтернативы вместе — выбросы, расстояние и экологический эффект сразу.',
    landingFeatureHistoryTitle: 'История поездок',
    landingFeatureHistoryDesc:
      'Войдите в аккаунт, чтобы сохранять маршруты, отслеживать общий углеродный след и анализировать привычки поездок.',
    aboutBadge: 'О проекте',
    aboutTitle: 'О EcoRoute',
    aboutIntro:
      'EcoRoute — это студенческий проект, призванный сделать выбросы от поездок видимыми и сопоставимыми. Мы верим, что осознанный выбор меняет мир — знание воздействия поездки на окружающую среду помогает принимать решения в соответствии с вашими ценностями.',
    aboutMissionTitle: 'Наша миссия',
    aboutMission:
      'Мы работаем над ЦУР ООН 13 (борьба с изменением климата), предоставляя доступные и точные данные о выбросах для авиа- и наземных поездок. Вместо собственных оценок мы опираемся на авторитетные внешние источники, чтобы данные были максимально надёжными.',
    aboutHowItWorksTitle: 'Как это работает',
    aboutFlightEmissionsTitle: 'Выбросы авиарейсов — Google Travel Impact Model (TIM)',
    aboutFlightEmissions:
      'Все значения CO₂ для рейсов поступают из API Google Travel Impact Model. TIM — это open source-модель, использующая реальные типы самолётов, конфигурации кресел, коэффициенты загрузки и данные маршрутов для оценки выбросов на пассажира по классу салона. Она также показывает категорию шлейфов (низкая / средняя / высокая), указывающую на не-CO₂ вклад в потепление для конкретного рейса.',
    aboutFlightDistanceTitle: 'Расстояние авиа-маршрута',
    aboutFlightDistance:
      'рассчитывается локально по формуле гаверсина между аэропортами с добавлением 95 км на отклонения реальных маршрутов. Это используется только для отображения — значение выбросов берётся из TIM.',
    aboutCarDistanceTitle: 'Расстояние автомобильного маршрута',
    aboutCarDistance:
      'получается из API OSRM (Open Source Routing Machine), который возвращает фактическое дорожное расстояние и время в пути между двумя городами. Затем выбросы рассчитываются с коэффициентом 0,21 кг CO₂ на км, основанным на типичном европейском легковом автомобиле.',
    aboutTrainTitle: 'Сравнение с поездом',
    aboutTrain:
      'использует расстояние по прямой между городами с коэффициентом выбросов 0,041 кг CO₂ на км, отражающим средние европейские железнодорожные выбросы с учётом электросети.',
    aboutCompareTitle: 'Сравните варианты',
    aboutCompare:
      'EcoRoute позволяет сравнить выбросы рейса с альтернативами на автомобиле и поезде рядом. Используйте планировщик, чтобы понять реальную климатическую цену поездки и найти более экологичные способы путешествовать.',
    accountLoggedOut: 'Чтобы увидеть историю, нужно войти в систему.',
    accountLabel: 'Аккаунт',
    accountTitle: 'Моя история',
    accountLoading: 'Загрузка истории…',
    accountNoHistory: 'Истории пока нет.',
    accountNoHistoryHint:
      'Спланируйте поездку на главной странице, и она автоматически сохранится здесь.',
    accountSavedTrips: '{count} сохранённых поездок',
    accountClearAll: 'Очистить всё',
    accountConfirmClear: 'Вы уверены, что хотите очистить всю историю?',
    accountRemove: 'Удалить',
    plannerLabel: 'Планировщик EcoRoute',
    plannerTitle: 'Планировщик выбросов авиарейсов',
    plannerHideMap: 'Скрыть карту',
    plannerShowMap: 'Показать карту',
    plannerFavorites: 'Избранное',
    plannerLoad: 'Загрузить',
    plannerUseCurrentLocationLoading: 'Получение местоположения...',
    plannerUseCurrentLocation: 'Использовать текущее местоположение',
    plannerSaveToHistory: 'Сохранить в историю',
    plannerSaveAsFavorite: 'Сохранить в избранное',
    plannerGeoUnsupported: 'Геолокация не поддерживается этим браузером.',
    plannerGeoLoading: 'Получение вашего текущего местоположения...',
    plannerGeoUsingLocation: 'Используется ваше текущее местоположение: {city}, {country}',
    plannerGeoDenied: 'Доступ к местоположению запрещён. Разрешите доступ, чтобы использовать эту функцию.',
    plannerGeoUnavailable: 'Информация о местоположении недоступна.',
    plannerGeoTimeout: 'Запрос местоположения превысил время ожидания.',
    plannerGeoError: 'Не удалось получить ваше местоположение.',
    plannerSavedHistory: 'Рейс сохранён в историю.',
    plannerSavedFavorite: 'Сохранено в избранное.',
    cityFrom: 'Откуда',
    cityTo: 'Куда',
    citySearchPlaceholder: 'Поиск страны, города или кода аэропорта…',
    citySearchAria: 'Поиск города и страны для {label}',
    cityTopResults: 'Показаны 50 лучших результатов. Уточните запрос для более точного выбора.',
    cityNoMatches: 'Подходящие города не найдены.',
    travelCabinClass: 'Класс обслуживания',
    travelEconomy: 'Эконом',
    travelBusiness: 'Бизнес',
    travelFirst: 'Первый',
    travelNumberOfTravelers: 'Количество путешественников',
    emissionsFetching: 'Получение выбросов из TIM API…',
    emissionsEstimateWarning: 'Данные в реальном времени недоступны — показана оценка на основе стандартных факторов',
    emissionsTitle: 'Выбросы CO₂',
    emissionsPerPerson: 'На человека:',
    emissionsFlightDistance: 'дальность полёта (включая маршрут)',
    emissionsDrivingEquivalent: 'на автомобиле',
    emissionsTreesNeeded: 'дерев{suffix} требуется для компенсации (1 год)',
    emissionsTravelersTotal: 'путешественник{suffix} всего',
    comparisonTitle: 'Сравнение видов транспорта',
    comparisonFlight: 'Рейс',
    comparisonCar: 'Авто',
    comparisonTrain: 'Поезд',
    legsDirectFlight: 'Прямой рейс',
    legsFlightRoute: 'Маршрут рейса · {count} сегм.',
    flightHistoryEmptyTitle: 'Пока нет сохранённых рейсов',
    flightHistoryEmptyHint: 'Найдите рейс, чтобы добавить его в историю',
    flightHistoryTitle: 'История ваших рейсов ({count})',
    flightHistoryClearAll: 'Очистить всю историю',
    flightHistoryDelete: 'Удалить',
    mapHideAirports: 'Скрыть аэропорты',
    mapShowAirports: 'Показать аэропорты',
    mapTransferLabel: 'Пересадка:',
  },
  zh: {
    navbarHome: '首页',
    navbarPlanner: '规划器',
    navbarAbout: '关于',
    navbarHistory: '我的历史',
    navbarMenuOpen: '打开菜单',
    navbarMenuClose: '关闭菜单',
    languageSwitch: '语言',
    authLoading: '加载中...',
    authLogIn: '登录',
    authLogOut: '退出登录',
    authSignUp: '注册',
    loginTabLogIn: '登录',
    loginTabSignUp: '注册',
    loginEmail: '电子邮箱',
    loginPassword: '密码',
    loginEmailPlaceholder: 'you@example.com',
    loginPasswordPlaceholder: '••••••••',
    loginCancel: '取消',
    loginError: '发生错误',
    landingBadge: '可持续旅行规划器',
    landingTitleLine1: '更聪明地旅行。',
    landingTitleLine2: '了解你的碳足迹。',
    landingDescription: '比较全球航班、火车和汽车的排放。',
    landingPlanRoute: '规划你的路线 →',
    landingHowItWorks: '工作原理',
    landingFeaturesTitle: '为什么选择 EcoRoute？',
    landingSaveJourneysTitle: '保存你的旅程',
    landingSaveJourneysDesc: '创建免费账户以跟踪路线、监控碳足迹变化，并回顾之前的比较结果。',
    landingCreateAccount: '创建免费账户',
    landingAlreadyHaveAccount: '已有账户？登录',
    landingBottomTitle: '准备规划更绿色的旅程了吗？',
    landingBottomDesc: '开始比较路线，看看你能节省多少 CO₂。',
    landingOpenPlanner: '打开规划器 →',
    landingFeatureFlightTitle: '航班排放',
    landingFeatureFlightDesc: '使用 ICAO 认证的方法、舱位倍数和 RFI 计算每个航班的准确 CO₂ 排放。',
    landingFeatureAlternativesTitle: '更绿色的替代方案',
    landingFeatureAlternativesDesc: '发现欧洲范围内更低排放的火车和多式联运路线，作为飞行替代方案。',
    landingFeatureCompareTitle: '并排比较',
    landingFeatureCompareDesc: '将航班与替代方案放在一起查看——排放、距离和环保影响一目了然。',
    landingFeatureHistoryTitle: '旅程历史',
    landingFeatureHistoryDesc: '登录后可保存路线、跟踪你的总碳足迹，并随时间查看出行习惯。',
    aboutBadge: '关于',
    aboutTitle: '关于 EcoRoute',
    aboutIntro:
      'EcoRoute 是一个学生项目，旨在让旅行排放变得可见且可比较。我们相信，有信息支撑的选择会推动改变——了解旅程的环境影响能帮助你做出符合价值观的决定。',
    aboutMissionTitle: '我们的使命',
    aboutMission:
      '我们致力于联合国可持续发展目标 13（气候行动），为航空和地面旅行提供可访问、准确的排放数据。我们不自行估算排放，而是依赖权威的外部数据来源，让你看到的数值尽可能可靠。',
    aboutHowItWorksTitle: '工作原理',
    aboutFlightEmissionsTitle: '航班排放 — Google Travel Impact Model (TIM)',
    aboutFlightEmissions:
      '所有航班 CO₂ 数据都来自 Google 的 Travel Impact Model API。TIM 是一个开源模型，使用真实机型、座位配置、载客率和航线数据，按舱位估算每位乘客的排放。它还会返回尾迹影响等级（低 / 中 / 高），用于表示特定航班的非 CO₂ 增温影响。',
    aboutFlightDistanceTitle: '航线距离',
    aboutFlightDistance:
      '使用机场之间的 Haversine 公式在本地计算，并增加 95 公里的绕行系数以适应真实路线。这只用于展示——排放数值本身来自 TIM。',
    aboutCarDistanceTitle: '公路距离',
    aboutCarDistance:
      '通过 OSRM API（Open Source Routing Machine）获取，该接口返回两座城市之间的实际道路距离和驾驶时间。随后按 0.21 kg CO₂/公里 的系数计算排放，基于典型的欧洲乘用车。',
    aboutTrainTitle: '火车比较',
    aboutTrain:
      '使用城市间的直线距离，并采用 0.041 kg CO₂/公里 的排放系数，反映平均欧洲铁路排放（含电网结构）。',
    aboutCompareTitle: '比较你的选择',
    aboutCompare:
      'EcoRoute 让你将航班排放与汽车和火车替代方案并排比较。使用规划器了解旅程真实的气候成本，并发现低影响的出行方式。',
    accountLoggedOut: '你必须登录后才能查看历史记录。',
    accountLabel: '账户',
    accountTitle: '我的历史',
    accountLoading: '正在加载历史…',
    accountNoHistory: '还没有历史记录。',
    accountNoHistoryHint:
      '在首页规划一次旅程，它会自动保存在这里。',
    accountSavedTrips: '已保存 {count} 次行程',
    accountClearAll: '全部清除',
    accountConfirmClear: '你确定要清除所有历史记录吗？',
    accountRemove: '移除',
    plannerLabel: 'EcoRoute 规划器',
    plannerTitle: '航班排放规划器',
    plannerHideMap: '隐藏地图',
    plannerShowMap: '显示地图',
    plannerFavorites: '收藏',
    plannerLoad: '加载',
    plannerUseCurrentLocationLoading: '正在获取位置...',
    plannerUseCurrentLocation: '使用当前位置',
    plannerSaveToHistory: '保存到历史',
    plannerSaveAsFavorite: '保存为收藏',
    plannerGeoUnsupported: '此浏览器不支持地理定位。',
    plannerGeoLoading: '正在获取你的当前位置...',
    plannerGeoUsingLocation: '正在使用你的当前位置：{city}, {country}',
    plannerGeoDenied: '已拒绝位置访问。请允许位置访问以使用此功能。',
    plannerGeoUnavailable: '位置信息不可用。',
    plannerGeoTimeout: '位置请求超时。',
    plannerGeoError: '无法获取你的位置。',
    plannerSavedHistory: '航班已保存到历史。',
    plannerSavedFavorite: '已保存为收藏。',
    cityFrom: '从',
    cityTo: '到',
    citySearchPlaceholder: '搜索国家、城市或机场代码…',
    citySearchAria: '{label} 城市和国家搜索',
    cityTopResults: '显示前 50 个结果。缩小搜索范围可获得更具体的选项。',
    cityNoMatches: '未找到匹配的城市。',
    travelCabinClass: '舱位',
    travelEconomy: '经济舱',
    travelBusiness: '商务舱',
    travelFirst: '头等舱',
    travelNumberOfTravelers: '旅客人数',
    emissionsFetching: '正在从 TIM API 获取排放数据…',
    emissionsEstimateWarning: '实时数据不可用 — 显示基于标准排放因子的估算值',
    emissionsTitle: 'CO₂ 排放',
    emissionsPerPerson: '人均：',
    emissionsFlightDistance: '航班距离（含路线）',
    emissionsDrivingEquivalent: '相当于汽车',
    emissionsTreesNeeded: '棵树用于抵消（1 年）',
    emissionsTravelersTotal: '位旅客总计',
    comparisonTitle: '交通方式比较',
    comparisonFlight: '航班',
    comparisonCar: '汽车',
    comparisonTrain: '火车',
    legsDirectFlight: '直飞',
    legsFlightRoute: '航线 · {count} 段',
    flightHistoryEmptyTitle: '尚未保存航班',
    flightHistoryEmptyHint: '搜索一个航班即可添加到历史记录',
    flightHistoryTitle: '你的航班历史（{count}）',
    flightHistoryClearAll: '清空全部历史',
    flightHistoryDelete: '删除',
    mapHideAirports: '隐藏机场',
    mapShowAirports: '显示机场',
    mapTransferLabel: '中转：',
  },
}

type LanguageContextValue = {
  language: Language
  languageLabel: string
  supportedLanguages: Language[]
  setLanguage: (language: Language) => void
  toggleLanguage: () => void
  t: (key: TranslationKey, params?: TranslationParams) => string
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined)

function detectInitialLanguage(): Language {
  if (typeof window === 'undefined') {
    return 'en'
  }

  const storedLanguage = window.localStorage.getItem(STORAGE_KEY)
  if (storedLanguage && supportedLanguages.includes(storedLanguage as Language)) {
    return storedLanguage as Language
  }

  const browserLanguage = window.navigator.language.toLowerCase()
  if (browserLanguage.startsWith('sv')) return 'sv'
  if (browserLanguage.startsWith('es')) return 'es'
  if (browserLanguage.startsWith('fr')) return 'fr'
  if (browserLanguage.startsWith('de')) return 'de'
  if (browserLanguage.startsWith('it')) return 'it'
  if (browserLanguage.startsWith('ru')) return 'ru'
  if (browserLanguage.startsWith('zh') || browserLanguage.startsWith('cn')) return 'zh'
  return 'en'
}

function formatTranslation(template: string, params?: TranslationParams) {
  if (!params) return template

  return template.replace(/\{(\w+)\}/g, (_, token: string) => {
    const value = params[token]
    return value === undefined ? `{${token}}` : String(value)
  })
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(detectInitialLanguage)
  const currentLanguage = language as Language

  useEffect(() => {
    window.localStorage.setItem(STORAGE_KEY, language)
    document.documentElement.lang = language
  }, [language])

  const value = useMemo<LanguageContextValue>(() => {
    return {
      language: currentLanguage,
      languageLabel: languageLabels[currentLanguage],
      supportedLanguages,
      setLanguage: setLanguageState,
      toggleLanguage: () => {
        const currentIndex = supportedLanguages.indexOf(currentLanguage)
        const nextLanguage = supportedLanguages[(currentIndex + 1) % supportedLanguages.length]
        setLanguageState(nextLanguage)
      },
      t: (key: TranslationKey, params?: TranslationParams) => {
        const translatedValue = translations[currentLanguage][key] ?? englishTranslations[key]
        return formatTranslation(translatedValue, params)
      },
    }
  }, [language])

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)

  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }

  return context
}
